CalDAV Integration
m-ld/timeld pull request #80
Opened 2022-09-06 13:15 UTC by gsvarovsky

Closes #71: Instance-specific integration configuration
Closes #24: Importing timesheet entries from CalDAV

2022-09-07 12:18 UTC, gsvarovsky commented
@Angus-McAllister : READMEs to review in this PR:
- packages/cli/README.md (note, links to not yet published npm repos)
- packages/caldav/README.md
- packages/prejournal/README.md
- packages/tiki/README.md

2022-09-07 15:00 UTC, Angus-McAllister requested changes
Most comments relate to our earlier conversation about disambiguating the term "integration" by introducing "connector".

2022-09-07 15:00 UTC, Angus-McAllister commented on packages/caldav/README.md
> +This packages supports live update of timesheet entries:
Should be "package" singular, rather than plural

2022-09-07 15:00 UTC, Angus-McAllister commented on packages/caldav/README.md
> +- _from_ a CalDAV end-point
I'd suggest adding an example here along the lines of "such as iCloud Calendar".

2022-09-07 15:00 UTC, Angus-McAllister commented on packages/caldav/README.md
> +This integration package is included in the gateway.
I'd suggest capitalising "Gateway", to ensure readers know the documentation is referring to a specific timeld component.

2022-09-07 15:00 UTC, Angus-McAllister commented on packages/caldav/README.md
> +- `uri`: calendar URI (https)
`url`, surely?  Rationale: it has to be reachable, so requires a concrete reference.

2022-09-07 15:00 UTC, Angus-McAllister commented on packages/caldav/README.md
> +- `pollInterval` CalDAV polling interval, in millis (optional; defaults to 10000)
For the time unit, either use the SI abbreviation "ms" or express it in full as "milliseconds".

2022-09-07 15:00 UTC, Angus-McAllister commented on packages/caldav/README.md
> +Configuration defaults may already be included in the gateway. Timesheet-specific configuration can also be included when adding the integration, see below.
1. Ditto re: case of "Gateway".
2. As per conversation, replace "integration" with "connector".

2022-09-07 15:00 UTC, Angus-McAllister commented on packages/caldav/README.md
> +To activate the integration for a timesheet "my-work" (note this assumes authorisation has defaults in the gateway).
Ditto re: case of "Gateway"

2022-09-07 15:00 UTC, Angus-McAllister commented on packages/caldav/README.md
> +alice> add integration timeld-caldav --ts my-work --config.uri "https://p116-caldav.icloud.com/151157399/calendars/work"
As per earlier conversation, replace `integration` with `connector`.

2022-09-07 15:00 UTC, Angus-McAllister commented on README.md
> +- Submit completed timesheets to other management systems
I'd suggest the term "time-tracking systems" in preference to "management systems".

2022-09-07 15:00 UTC, Angus-McAllister commented on README.md
> +- Import timesheets from other management systems
Ditto re: "time-tracking systems"

2022-09-07 15:00 UTC, Angus-McAllister commented on packages/cli/README.md
> +add integration ≪integration-module≫ --timesheet my-timesheet --config.≪key≫ ≪config-value≫
As per earlier conversation, replace `integration` with `connector` in each case.

2022-09-07 15:00 UTC, Angus-McAllister commented on packages/cli/README.md
> +| system                                                                       | integration module                                                   |
Nice improvement to the formatting.

2022-09-07 15:00 UTC, Angus-McAllister commented on packages/cli/README.md
> +- `≪integration-module≫` is `timeld-prejournal`, `timeld-tiki`, or `timeld-caldav`
1. Ditto re: `connector`
2. I'd suggest "is one of `timeld-prejournal,`" etc.

2022-09-07 15:00 UTC, Angus-McAllister commented on packages/cli/README.md
> +- `≪key≫` and `≪config-value≫` are any configuration required for the integration (see integration module links above)
Ditto re: `connector`

2022-09-07 15:00 UTC, Angus-McAllister commented on packages/prejournal/README.md
> +# timeld - Prejournal integration
In view of earlier conversation, would suggest "PreJournal Connector for timeld".

2022-09-07 15:00 UTC, Angus-McAllister commented on packages/prejournal/README.md
> +This packages supports live update of timesheet entries:
"packages" should be singular.

2022-09-07 15:00 UTC, Angus-McAllister commented on packages/prejournal/README.md
> +This integration package is included in the gateway.
As per earlier conversation, replace "integration package" with "connector".

2022-09-07 15:00 UTC, Angus-McAllister commented on packages/prejournal/README.md
> +The integration requires the following configuration:
Ditto re: "connector"

2022-09-07 15:00 UTC, Angus-McAllister commented on packages/prejournal/README.md
> +Configuration defaults may already be included in the gateway. Timesheet-specific configuration can also be included when adding the integration, see below.
1. As mentioned in earlier comment on another README.md in this review, would recommend capitalising "Gateway"; and
2. Replace "integration" with "connector".

2022-09-07 15:00 UTC, Angus-McAllister commented on packages/prejournal/README.md
> +To activate the integration for a timesheet "my-work" (note this assumes authorisation and API defaults in the gateway).
Ditto re: "connector".

2022-09-07 15:00 UTC, Angus-McAllister commented on packages/tiki/README.md
> +alice> add integration timeld-tiki --ts my-work --config.api "https://timesheet.dev3.evoludata.com/api/trackers/2/items"
Ditto re: `connector`.

2022-09-09 10:37 UTC, Angus-McAllister approved these changes
Perfect, thx :-)

2022-09-09 11:02 UTC, merged